# Generated by Django 5.1.1 on 2024-10-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpostsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostsection',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostsection',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpostsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/images/'),
        ),
        migrations.AlterField(
            model_name='blogpostsection',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blogpostsection',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sections/videos/'),
        ),
    ]
