# Generated by Django 5.1.1 on 2024-10-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpostsection_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='BlogPostSection',
        ),
    ]
