# Generated by Django 5.1.1 on 2024-10-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_sections_delete_blogpostsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='excerpt',
        ),
    ]
