# Generated by Django 5.1.1 on 2024-10-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpost_content_remove_blogpost_excerpt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='video',
        ),
    ]
