# Generated by Django 5.1.1 on 2024-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_event_image_remove_featurenews_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='featurenews',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='author',
        ),
        migrations.RemoveField(
            model_name='trendingnews',
            name='author',
        ),
        migrations.AddField(
            model_name='event',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='featurenews',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='feature_news/images/'),
        ),
        migrations.AddField(
            model_name='featurenews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feature_news/'),
        ),
        migrations.AddField(
            model_name='mainarticle',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='main_articles/images/'),
        ),
        migrations.AddField(
            model_name='mainarticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_articles/'),
        ),
        migrations.AddField(
            model_name='trendingnews',
            name='additional_images',
            field=models.ImageField(blank=True, null=True, upload_to='trending_news/images/'),
        ),
        migrations.AddField(
            model_name='trendingnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trending_news/'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
