# Generated by Django 5.1.1 on 2024-10-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_event_author_featurenews_author_mainarticle_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='featurenews',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='trendingnews',
            name='video_url',
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='featurenews',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='mainarticle',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='trendingnews',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
