# Generated by Django 5.1.1 on 2024-10-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_event_video_url_remove_featurenews_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainarticle',
            name='additional_images',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='content',
        ),
        migrations.RemoveField(
            model_name='mainarticle',
            name='subtitle',
        ),
    ]
