# Generated by Django 5.1.1 on 2024-10-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_mainarticle_additional_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainarticle',
            name='video',
        ),
    ]
