# Generated by Django 3.2.10 on 2024-09-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeshara', '0002_auto_20240915_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
