# Generated by Django 5.1.1 on 2024-09-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeshara', '0003_alter_property_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='for_sale',
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold'), ('rented', 'Rented'), ('co_living', 'Co-living')], default='for_sale', max_length=20),
        ),
    ]
